# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ADCS_test_unit_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(140, 60)
        Frame.setFrameShape(QtWidgets.QFrame.Panel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.RunCB = QtWidgets.QCheckBox(Frame)
        self.RunCB.setObjectName("RunCB")
        self.verticalLayout.addWidget(self.RunCB)
        self.dataLabel = QtWidgets.QLabel(Frame)
        self.dataLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.dataLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dataLabel.setObjectName("dataLabel")
        self.verticalLayout.addWidget(self.dataLabel)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.RunCB.setText(_translate("Frame", "Имя параметра:"))
        self.dataLabel.setText(_translate("Frame", "---"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
