# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_unit_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dataUnitFrame(object):
    def setupUi(self, dataUnitFrame):
        dataUnitFrame.setObjectName("dataUnitFrame")
        dataUnitFrame.resize(413, 750)
        dataUnitFrame.setMinimumSize(QtCore.QSize(0, 480))
        dataUnitFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.gridLayout = QtWidgets.QGridLayout(dataUnitFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.GNSSValidrame = QtWidgets.QFrame(dataUnitFrame)
        self.GNSSValidrame.setMinimumSize(QtCore.QSize(140, 60))
        self.GNSSValidrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GNSSValidrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GNSSValidrame.setObjectName("GNSSValidrame")
        self.gridLayout.addWidget(self.GNSSValidrame, 3, 0, 1, 1)
        self.MagVecFrame = QtWidgets.QFrame(dataUnitFrame)
        self.MagVecFrame.setMinimumSize(QtCore.QSize(140, 60))
        self.MagVecFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MagVecFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MagVecFrame.setObjectName("MagVecFrame")
        self.gridLayout.addWidget(self.MagVecFrame, 2, 1, 1, 1)
        self.AngVelFrame = QtWidgets.QFrame(dataUnitFrame)
        self.AngVelFrame.setMinimumSize(QtCore.QSize(140, 60))
        self.AngVelFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AngVelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AngVelFrame.setObjectName("AngVelFrame")
        self.gridLayout.addWidget(self.AngVelFrame, 6, 1, 1, 1)
        self.GNSSTimeFrame = QtWidgets.QFrame(dataUnitFrame)
        self.GNSSTimeFrame.setMinimumSize(QtCore.QSize(140, 60))
        self.GNSSTimeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GNSSTimeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GNSSTimeFrame.setObjectName("GNSSTimeFrame")
        self.gridLayout.addWidget(self.GNSSTimeFrame, 4, 0, 1, 1)
        self.GNSSCoordFrame = QtWidgets.QFrame(dataUnitFrame)
        self.GNSSCoordFrame.setMinimumSize(QtCore.QSize(140, 60))
        self.GNSSCoordFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.GNSSCoordFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.GNSSCoordFrame.setObjectName("GNSSCoordFrame")
        self.gridLayout.addWidget(self.GNSSCoordFrame, 6, 0, 1, 1)
        self.MagAbsFrame = QtWidgets.QFrame(dataUnitFrame)
        self.MagAbsFrame.setMinimumSize(QtCore.QSize(140, 60))
        self.MagAbsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MagAbsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MagAbsFrame.setObjectName("MagAbsFrame")
        self.gridLayout.addWidget(self.MagAbsFrame, 1, 1, 1, 1)
        self.infoCB = QtWidgets.QCheckBox(dataUnitFrame)
        self.infoCB.setMinimumSize(QtCore.QSize(0, 30))
        self.infoCB.setObjectName("infoCB")
        self.gridLayout.addWidget(self.infoCB, 0, 0, 1, 2)
        self.RebootCtrFrame = QtWidgets.QFrame(dataUnitFrame)
        self.RebootCtrFrame.setMinimumSize(QtCore.QSize(140, 60))
        self.RebootCtrFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RebootCtrFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RebootCtrFrame.setObjectName("RebootCtrFrame")
        self.gridLayout.addWidget(self.RebootCtrFrame, 1, 0, 1, 1)
        self.TempFrame = QtWidgets.QFrame(dataUnitFrame)
        self.TempFrame.setMinimumSize(QtCore.QSize(140, 60))
        self.TempFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TempFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TempFrame.setObjectName("TempFrame")
        self.gridLayout.addWidget(self.TempFrame, 2, 0, 1, 1)
        self.AccelFrame = QtWidgets.QFrame(dataUnitFrame)
        self.AccelFrame.setMinimumSize(QtCore.QSize(140, 60))
        self.AccelFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AccelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AccelFrame.setObjectName("AccelFrame")
        self.gridLayout.addWidget(self.AccelFrame, 3, 1, 1, 1)
        self.LTimeFrame = QtWidgets.QFrame(dataUnitFrame)
        self.LTimeFrame.setMinimumSize(QtCore.QSize(140, 60))
        self.LTimeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LTimeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LTimeFrame.setObjectName("LTimeFrame")
        self.gridLayout.addWidget(self.LTimeFrame, 4, 1, 1, 1)

        self.retranslateUi(dataUnitFrame)
        QtCore.QMetaObject.connectSlotsByName(dataUnitFrame)

    def retranslateUi(self, dataUnitFrame):
        _translate = QtCore.QCoreApplication.translate
        dataUnitFrame.setWindowTitle(_translate("dataUnitFrame", "Frame"))
        self.infoCB.setText(_translate("dataUnitFrame", "Общая информация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dataUnitFrame = QtWidgets.QFrame()
    ui = Ui_dataUnitFrame()
    ui.setupUi(dataUnitFrame)
    dataUnitFrame.show()
    sys.exit(app.exec_())
