# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_unit_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_testUnitFrame(object):
    def setupUi(self, testUnitFrame):
        testUnitFrame.setObjectName("testUnitFrame")
        testUnitFrame.resize(830, 289)
        self.verticalLayout = QtWidgets.QVBoxLayout(testUnitFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.testLogTEdit = QtWidgets.QTextEdit(testUnitFrame)
        self.testLogTEdit.setReadOnly(True)
        self.testLogTEdit.setObjectName("testLogTEdit")
        self.verticalLayout.addWidget(self.testLogTEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.testLaunchPButton = QtWidgets.QPushButton(testUnitFrame)
        self.testLaunchPButton.setMinimumSize(QtCore.QSize(153, 30))
        self.testLaunchPButton.setObjectName("testLaunchPButton")
        self.horizontalLayout.addWidget(self.testLaunchPButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(testUnitFrame)
        QtCore.QMetaObject.connectSlotsByName(testUnitFrame)

    def retranslateUi(self, testUnitFrame):
        _translate = QtCore.QCoreApplication.translate
        testUnitFrame.setWindowTitle(_translate("testUnitFrame", "Frame"))
        self.testLogTEdit.setHtml(_translate("testUnitFrame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.testLaunchPButton.setText(_translate("testUnitFrame", "Запуск тестов"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    testUnitFrame = QtWidgets.QFrame()
    ui = Ui_testUnitFrame()
    ui.setupUi(testUnitFrame)
    testUnitFrame.show()
    sys.exit(app.exec_())
